caps:
  platformName: Android
  platformVersion: !!str 10
  deviceName: Q5S5T19424004010
  appPackage: com.tencent.wework
  appActivity: .launch.LaunchSplashActivity
  noReset: True
  skipDeviceInitialization: True
  unicodeKeyboard: True
  resetKeyboard: True
  skipServerInstallation: True